= HTTP Client Library

image::https://img.shields.io/badge/xp-7.+-blue.svg[role="right"]

Easily access remote web API's and data sources over HTTP using this library.

To start using this library, add the following into your `build.gradle` file:

[source,groovy]
----
dependencies {
  include 'com.enonic.lib:lib-http-client:2.4.1'
}
----

== Usage

To use this library in your JavaScript code, it first needs to be required:

[source,js]
----
var httpClient = require('/lib/http-client');
----

To make an HTTP or HTTPS request just call the `request` function with the desired parameters.

[source,js]
----
var response = httpClient.request({
    url: 'http://somehost/my/service', <1>
    method: 'POST',                    <2>
    headers: {
        'Cache-Control': 'no-cache'    <3>
    },
    connectionTimeout: 20000,          <4>
    readTimeout: 5000,                 <5>
    body: '{"id": 123}',               <6>
    contentType: 'application/json'    <7>
});
----
<1> The target URL for the request. Should be a valid _http://_ or _https://_ URL.
<2> The HTTP method, if omitted the GET method will be used.
<3> Optional request headers can be specified.
<4> Maximum time (ms) to wait for the connection to be established.
<5> Maximum time (ms) to wait for the server to send back data.
<6> The body of the HTTP request.
<7> The content type of the request.


The function will return an object with the properties of the HTTP response:

[source,js]
----
response = {
    'status': 200,               <1>
    'message': 'OK',             <2>
    'body': 'Response contents', <3>
    'contentType': 'text/plain', <4>
    'headers': {
        'Content-Length': '17',  <5>
        'content-type': 'text/plain'
    }
};
----
<1> HTTP status code.
<2> HTTP status message.
<3> Contents of the body if it's text. For binary contents see `bodyStream` property below.
<4> Content type of the response.
<5> Response HTTP headers.


== API

The following function is defined in this library.

=== `request(options)`

Sends an HTTP request and returns the response received from the remote server.
The request is made synchronously, that means the execution will block until the response is received.

*Parameters*

The request function takes a parameter object with options. The only mandatory option is the `url`.

* `options` (_object_) Parameters to make the HTTP request.
** `*url*` (_string_) URL to which the request is sent.
** `*method*` (_string_) The HTTP method to use for the request (e.g. "POST", "GET", "HEAD", "PUT", "DELETE", "PATCH"). The default value is `"GET"`.
** `*queryParams*` (_object_) [*v2.2.0+*] Query parameters to be sent with the request.
** `*params*` (_object_) Form parameters to be sent with the request. Will not be used if `*queryParams*` is provided.
** `*headers*` (_object_) HTTP headers, an object where the keys are header names and the values the header values.
** `*connectionTimeout*` (_number_) The timeout on establishing the connection, in milliseconds. The default value is `10000`.
** `*readTimeout*` (_number_) The timeout on waiting to receive data, in milliseconds. The default value is `10000`.
** `*body*` (_string_ | _object_) Body content to send with the request, usually for POST or PUT requests. It can be of type string or stream.
** `*contentType*` (_string_) Content type of the request.
** `*followRedirects*` (_boolean_) If set to `false`, redirect responses (status=`3xx`) will not trigger a new internal request, and the function will return directly with the `3xx` status. The default value `true`.
** `*multipart*` (_object[]_) Multipart form data to send with the request, an array of part objects. Each part object contains 'name', 'value', and optionally 'fileName' and 'contentType' properties. Where 'value' can be either a string or a Stream object.
** `*auth*` (_object_) Settings for basic authentication.
*** `*user*` (_string_) User name for basic authentication.
*** `*password*` (_string_) Password for basic authentication.
** `*proxy*` (_object_) Proxy settings.
*** `*host*` (_string_) Proxy host name or IP address to use.
*** `*port*` (_number_) Proxy port to use.
*** `*user*` (_string_) User name for proxy authentication.
*** `*password*` (_string_) Password for proxy authentication.
** `*certificates*` (_*_) Stream of PEM encoded certificates. Replaces the host platform's certificate authorities with a custom certificate.
** `*clientCertificate*` (_string |_*_) [*v2.3.0+*]
*** If value is `undefined` or empty string, first available alias in KeyStore is used. KeyStore specified by `com.enonic.lib.http.client.keyStore` system property. [*v2.4.0+*]
*** If value is typeof `string` and not empty it is interpreted as alias name in KeyStore. [*v2.4.0+*]
*** If type value is Stream, this Stream is interpreted as PEM encoded certificate: Private key (in PKCS #8 format) and the client certificate concatenated.
*** If value `null`, no client certificate is used.

*Returns*

The function will return a `response` object with the following properties:

* `*status*` (_number_) HTTP status code returned.
* `*message*` (_string_) HTTP status message returned.
* `*headers*` (_object_) HTTP headers of the response.
* `*cookies*` (_object_) Array of HTTP cookies set in the response.
* `*contentType*` (_string_) Content type of the response.
* `*body*` (_string_) Body of the response as string. Null if the response content-type is not of type text.
* `*bodyStream*` (_object_) Body of the response as a stream object.

== KeyStore Configuration [*v2.4.0+*]

There are multiple system properties similar to Default JSSE KeyStore system properties https://docs.oracle.com/en/java/javase/11/security/java-secure-socket-extension-jsse-reference-guide.html#GUID-7D9F43B8-AABF-4C5B-93E6-3AFB18B66150
They allow to configure a KeyStore that stores a keypair to be used for mTLS authentication, if `clientCertificate` is not specified in the request options, or if `clientCertificate` is specified an alias name.

* `com.enonic.lib.http.client.keyStore` Path to the KeyStore file. No KeyStore is used, if not specified.
* `com.enonic.lib.http.client.keyStorePassword` KeyStore password.
* `com.enonic.lib.http.client.keyStoreType` KeyStore type. Default is a value returned by `KeyStore.getDefaultType()`.
* `com.enonic.lib.http.client.keyStoreProvider` KeyStore provider name.

NOTE: In case when `clientCertificate` is not specified (`undefined` or empty string) there must be only one alias in the KeyStore, and it must be an alias for a keypair with a certificate.

== Examples

=== `Basic Authentication`
[source,js]
----
var httpClient = require('/lib/http-client');

var response = httpClient.request({
    url: 'http://somehost/protected/service',
    method: 'GET',
    auth: {
        user: 'username',
        password: 'secret'
    }
});
----


=== `Request via Proxy`
[source,js]
----
var httpClient = require('/lib/http-client');

var response = httpClient.request({
    url: 'http://somehost/some/service',
    method: 'GET',
    proxy: {
        host: '172.16.0.42',
        port: 8080,
        user: 'admin',
        password: 'secret'
    }
});
----


=== `Multipart POST request`
[source,js]
----
var httpClient = require('/lib/http-client');

var response = httpClient.request({
    url: 'http://somehost/uploadMedia',
    method: 'POST',
    contentType: 'multipart/mixed',
    multipart: [
        {
            name: 'media',
            fileName: 'logo.png',
            contentType: 'image/png',
            value: myImageStream
        },
        {
            name: 'category',
            value: 'images'
        }
    ]
});
----

=== `Using custom certificate`
[source,js]
----
var httpClient = require('/lib/http-client');
var ioLib = require('/lib/xp/io');  // IO API library from XP
var token = app.config['token']; // Token stored in the application config file
var certificates = ioLib.newStream(app.config['certificates']); // Certificate stored in the application config file. NOTE: It is not a location of the certificate file, but body of the certificate itself.

var response = httpClient.request({
    url: 'http://somehost/some/service',
    method: 'POST',
    headers: {'Authorization': 'Bearer ' + token},
    contentType: 'application/json',
    certificates: certificates
});
----

== Compatibility

This library is not compatible with XP releases before version 7.0. Make sure you reference the lib as `/lib/http-client`
and not as `/lib/xp/http-client` or `/site/lib/xp/http-client`.
